spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco-de-sangue-dev?createDatabaseIfNotExist=true&serverTimezone=UTC-3&useSSl=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
server:
  port: 8080

app:
  feign:
    client:
      config:
        name: jsonLoaderClient
        url: https://cdn.ronilsonalves.com/testes/bancodesangue/data.json
        loggerLevel: basic

logging:
  level:
    com.ronilsonalves.bancodesangue.api.client: DEBUG
# Spring Docs
springdoc:
  packagesToScan:
    - com.ronilsonalves.bancodesangue.api.controller
  swagger-ui:
    path: /api-docs